apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
   name: my-demo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/deploy-cluster: test
  endpoints:
  - port: metrics
    interval: 30s
