apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector-scrape
rules:
# Rule 1: Allow getting /metrics from the Kubelet or other secure endpoints
- nonResourceURLs:
    - /metrics
  verbs:
    - get
# Rule 2: Allow getting/watching/listing basic resources (like Pods and Namespaces)
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
# Rule 3: Allow getting/watching/listing Deployments/ReplicaSets (in 'apps' group)
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch"]
# Rule 4: Allow getting/watching/listing Deployments/ReplicaSets (in 'extensions' group - for older K8s versions)
- apiGroups: ["extensions"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector-scrape
subjects:
- kind: ServiceAccount
  name: otel-collector-opentelemetry-collector
  namespace: opentelemetry
roleRef:
  kind: ClusterRole
  name: otel-collector-scrape
  apiGroup: rbac.authorization.k8s.io
