apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-persistentvolume-claim
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-storage
