name: build-docker-image-action
run-name: ${{ github.actor }} Build Docker Image
on:
  workflow_dispatch:
  push:
    branches:
       - 'main'
env:
  DOCKER_IMAGE_NAME: my-demo
  DOCKER_REGISTRY_URL: localhost:5000

jobs:
  build-image:
    name: Build Docker Image
    runs-on: self-hosted
  
    steps:
       - name: Checkout
         uses: actions/checkout@v4

       - name: Get the branch name
         id: get_version
         run: echo "VERSION=${GITHUB_REF#refs/branches/}" >> $GITHUB_OUTPUT

       #- name: Build image with Podman
       #  run: |
       #    podman build -t ${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_IMAGE_NAME }}:latest .

       - name: Build image with Buildah/Podman
         uses: redhat-actions/buildah-build@v2
         with:
           image: ${{ env.DOCKER_IMAGE_NAME }}
           tags: latest
           containerfiles: |
               ./Dockerfile

       - name: Push image to registry
         uses: redhat-actions/push-to-registry@v2
         with:
           image: ${{ env.DOCKER_IMAGE_NAME }}
           tags: latest
           registry: ${{ env.DOCKER_REGISTRY_URL }}
           tls-verify: false
