name: build-docker-image-action
run-name: ${{ github.actor }} Build Docker Image
on:
  workflow_dispatch:
  push:
    branches:
       - 'main'
env:
  DOCKER_IMAGE_NAME: my-demo
  DOCKER_REGISTRY_URL: localhost:5000

jobs:
  build-image:
    name: Build Docker Image
    runs-on: self-hosted
  
    steps:
       - name: Checkout
         uses: actions/checkout@v3

       - name: Setup Docker BuildX
         uses: docker/setup-buildx-action@v3a

       - name: Get the branch name
         id: get_version
         run: echo "VERSION=${GITHUB_REF#refs/branches/}" >> $GITHUB_OUTPUT

       - name: Build and Push Docker image
         uses: docker/build-push-action@v6
         with:
           context: .
           file: ./Dockerfile
           push: true
           tags: |
             ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
             ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:latest
           cache-from: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:buildcache
           cache-to: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:buildcache,mode=max
