name: Build Image
run-name: ${{ github.actor }} Build Docker Image
on:
  workflow_dispatch:
  push:
    branches:
       - 'main'

env:
  DOCKER_IMAGE_NAME: my-demo
  DOCKER_REGISTRY_URL: localhost:5000

jobs:
  opengrep:
    name: OpenGrep Scanner
    uses: ./.github/workflows/opengrep.yml
    # continue-on-error not supported right now

    permissions:
      contents: read
      actions: read
      security-events: write
      packages: read
 
  build-image:
    name: Build Docker Image
    runs-on: self-hosted
    needs: opengrep
  
    steps:
       - name: Checkout
         uses: actions/checkout@v4

       - name: Build image with Buildah/Podman
         uses: redhat-actions/buildah-build@v2
         with:
           image: ${{ env.DOCKER_IMAGE_NAME }}
           tags: latest
           containerfiles: |
               ./Dockerfile

       - name: Push image to registry
         uses: redhat-actions/push-to-registry@v2
         with:
           image: ${{ env.DOCKER_IMAGE_NAME }}
           tags: latest
           registry: ${{ env.DOCKER_REGISTRY_URL }}
           tls-verify: false
